services:
  frontend:
    build: ./hyper-city-frontend
    container_name: hypercity-frontend
    ports:
      - "32345:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:10000
    networks:
      - public

  backend:
    build: ./hyper-city-backend
    container_name: hypercity-backend
    ports:
      - "52345:10000"
    networks:
      - public

networks:
  public:
    external: true