services:
  frontend:
    build: ./hyper-city-frontend
    container_name: hypercity-frontend
    expose:
      - "3000"
    networks:
      - public

  backend:
    build: ./hyper-city-backend
    container_name: hypercity-backend
    expose:
      - "10000"
    networks:
      - public

  proxy:
    image: nginx:alpine
    container_name: hypercity-proxy
    ports:
      - "32345:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - public

networks:
  public:
    external: true